var rule ={
            title: '369看片',
            host: 'https://k.369ttkp3.live/',
            url: 'https://k.369ttkp3.live/wunsian.asp?page=fypage&fl=fyclass&pl=time',
            searchUrl: 'https://k.369ttkp3.live/search.asp?page=fypage&searchword=**&searchtype=-1',
            //class_parse: '#menu p;a&&Text;a&&href;.*/(.*?).html',
class_name:'电影&电视剧&动作片&香港TVB&动画片&综艺&你懂的电影&你懂的动画片',
class_url:'15&28&1&10&7&8&31&36',
            searchable: 2,
            quickSearch: 0,
            编码:'GBK',
            filterable: 0,
            headers: {
                'User-Agent': 'PC_UA',
            },
            play_parse: true,
            lazy: '',
            limit: 6,
            推荐: '.img-list;li;a&&title;img&&src;em&&Text;a&&href',
            double: true,
            一级: '.img-list&&li;a&&title;img&&src;em&&Text;a&&href',
            二级: {
                title: 'h1&&Text',
                img: '.vodlist_thumb&&data-original',
                desc: '.info&&li:eq(1) li&&Text;.info&&li:eq(2) li&&Text;.info&&li:eq(3) li&&Text;.info&&li:eq(4) li&&Text;.info&&li:eq(0) li&&Text',
                content: '.textdesc&&Text',
                tabs: '.banner p',
                lists: '.play-list:eq(#id) a',
            },
            搜索: '*',
        }